title: <p align="center"> Harshit Sharma </p>
logo: /assets/img/dp.PNG

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/harshit-sharma-980117168/">LinkedIn</a> |
  <a href="https://github.com/harshitsharma496">GitHub</a>
  
  <br>
  <br>
  
  I'm enthusiast of Data Science,Machine learning & NLP related problems.
  <br>
  <br>
  Currently working as a DBA at Infosys.
  </p>
  



